services:
  postgres:
    image: postgres:16
    container_name: kang_stock_db
    environment:
      POSTGRES_USER: kang
      POSTGRES_PASSWORD: rkdrlxo12
      POSTGRES_DB: kang_stock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kang -d kang_stock" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
